# Copyright 2023 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0

version: 2
project_name: vexctl

env:
  - GO111MODULE=on
  - COSIGN_YES=true

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true

builds:
  - id: binaries
    main: .
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - s390x
      - ppc64le
    goarm:
      - '7'
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env:
      - CGO_ENABLED=0

signs:
  - id: vexctl-keyless
    signature: "${artifact}"
    cmd: cosign
    args: ["sign-blob", "--bundle", "${artifact}.sigstore.json", "${artifact}"]
    artifacts: all

archives:
  - formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    allow_different_binary_count: true

sboms:
  - id: vexctl
    cmd: bom
    args:
      - generate
      - "--output"
      - "vexctl-bom.json.spdx"
      - "-d"
      - "../"
      - "-c"
      - "../.vexctl-bom-config.yaml"
      - "--format"
      - "json"
    artifacts: any
    documents:
      - "vexctl-bom.json.spdx"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  version_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: auto

changelog:
  use: github-native
