/*
Copyright 2022 The OpenVEX Authors
SPDX-License-Identifier: Apache-2.0
*/

package cmd

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"

	"github.com/google/go-containerregistry/pkg/name"
	"github.com/openvex/vexctl/pkg/attestation"
	"github.com/openvex/vexctl/pkg/ctl"
	"github.com/spf13/cobra"
)

type attestOptions struct {
	outFileOption
	attach       bool
	sign         bool
	format       string
	attachMethod string
	refs         []string
}

func (o *attestOptions) AddFlags(cmd *cobra.Command) {
	o.outFileOption.AddFlags(cmd)
	cmd.PersistentFlags().BoolVarP(
		&o.attach,
		"attach",
		"a",
		false,
		"attach the generated attestation to an image (implies --sign)",
	)

	cmd.PersistentFlags().BoolVarP(
		&o.sign,
		"sign",
		"s",
		false,
		"sign the attestation with sigstore",
	)

	cmd.PersistentFlags().StringArrayVarP(
		&o.refs,
		"refs",
		"r",
		[]string{},
		"list of image references to attach the attestation to",
	)

	cmd.PersistentFlags().StringVar(
		&o.attachMethod,
		"attach-method",
		string(ctl.DefaultAttachMethod),
		fmt.Sprintf(
			"method used to attach attestations to images (%s or %s)",
			ctl.AttachMethodReferrers, ctl.AttachMethodLegacy,
		),
	)

	cmd.PersistentFlags().StringVar(
		&o.format,
		"format",
		string(attestation.DefaultFormat),
		fmt.Sprintf(
			"output format of signed attestations (%s or %s)",
			attestation.FormatBundle, attestation.FormatDSSE,
		),
	)
}

// Validate checks if the options are sane
func (o *attestOptions) Validate() error {
	var sErr error
	for _, ref := range o.refs {
		if _, err := name.ParseReference(ref); err != nil {
			sErr = fmt.Errorf("parsing reference: %w", err)
			break
		}
	}

	if o.attach {
		o.sign = true
	}

	_, fErr := attestation.ParseFormat(o.format)
	_, mErr := ctl.ParseAttachMethod(o.attachMethod)

	return errors.Join(
		sErr, fErr, mErr, o.outFileOption.Validate(),
	)
}

func addAttest(parentCmd *cobra.Command) {
	opts := attestOptions{}
	attestCmd := &cobra.Command{
		Short: fmt.Sprintf("%s attest: generate a VEX  attestation", appname),
		Long: fmt.Sprintf(`%s attest: generate an VEX attestation

The attach subcommand lets users wrap OpenVEX documents in in-toto attestations.
Attestations generated by %s can be signed with sigstore and attached to
container images stored in an OCI registry.

In its simplest form, %s will create an attestation from an OpenVEX file and
write it to stdout:

  %s attest data.vex.json

Without any more arguments, container images and other products that have hashes
defined in their VEX statements, will be read by %s and transferred to
the attestation's subjects when required.

If the products are purls of type oci:, they will be converted to image
references as is customary in the sigstore tooling. For example:

If a product identified by the following package URL is found in a statement:

  pkg:oci/kube-apiserver?repository_url=registry.k8s.io&tag=v1.26.0

It will be transferred to the attestation subjects as:

  registry.k8s.io/kube-apiserver:v1.26.0

Any oci purls and image references not specifying a digest will trigger a
network lookup to read the image digest from the registry.

Please note that purls of types other than oci: and other strings which are not
valid image references will not be included in the resulting attestation unless 
the product has hashes associated with it. 

Signing Attestations
--------------------

Passing the --sign flag will trigger the sigstore signing flow, either asking for
credentials from the user or trying to get them from the environment:

  %s attest --sign data.vex.json

When signing an attestation, the standard sigstore signing flow will be triggered
if credentials are not found in the environment. Refer to the sigstore
documentation for details.

Signed attestations are written as sigstore bundles. The bundle wraps the
signed attestation together with the signing certificate and its transparency
log entry, which makes it verifiable on its own. To write only the DSSE
envelope, as previous versions of %s did, use --format dsse:

  %s attest --sign --format dsse data.vex.json

Note that a bare DSSE envelope signed with a sigstore certificate cannot be
verified by itself as the certificate is not part of the envelope.

Attaching Attestations
----------------------

The --attach flag will attach the resulting attestation to the OCI registry of
all subjects that parse as image references. If this behavior fails, try defining
--refs to specify which images to attach the attestation to.

%s will use the credentials from the user's environment to authenticate to the
registry, this means that if you can write to the registry, attaching should work.

By default, attestations are attached as sigstore bundles that refer to the
image through the OCI referrers API, the layout used by cosign v3. To attach
the attestation as a DSSE envelope in the cosign tag layout (the .att tag next
to the image) used by older versions of cosign and %s, use --attach-method:

  %s attest --attach --attach-method legacy vex.json user/test

Note: --attach always implies --sign as sigstore does not support attaching
unsigned attestations.

Specifying Images to Attest
---------------------------

If any further positional arguments are defined, they will be interpreted as
products/image references. %s will generate and attach (if applicable) the
attestation only for those images, not transferring other products in the
VEX document as in-toto subjects. 

For example, the following invocation will only attest and attach vex.json
to user/test, even if the OpenVEX document has product entries for other images:

%s attest --attach vex.json user/test


`, appname, appname, appname, appname, appname, appname, appname, appname, appname, appname, appname, appname, appname),
		Use:               "attest [flags] openvex.json",
		SilenceUsage:      false,
		SilenceErrors:     false,
		PersistentPreRunE: initLogging,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return errors.New("not enough arguments")
			}

			if err := opts.Validate(); err != nil {
				return fmt.Errorf("validating options: %w", err)
			}

			cmd.SilenceUsage = true
			ctx := context.Background()

			attachMethod, err := ctl.ParseAttachMethod(opts.attachMethod)
			if err != nil {
				return err
			}

			vexctl := ctl.New()
			vexctl.Options.Sign = opts.sign
			vexctl.Options.AttachMethod = attachMethod

			att, err := vexctl.Attest(args[0], args[1:])
			if err != nil {
				return fmt.Errorf("generating attestation: %w", err)
			}

			if opts.attach {
				if err := vexctl.Attach(ctx, att); err != nil {
					return fmt.Errorf("attaching attestation: %w", err)
				}
			}

			var out io.Writer = os.Stdout
			if opts.outFilePath != "" {
				out, err = os.Create(opts.outFilePath)
				if err != nil {
					return fmt.Errorf("opening attestation file: %w", err)
				}
			}
			format, err := attestation.ParseFormat(opts.format)
			if err != nil {
				return err
			}
			if err := att.Write(out, format); err != nil {
				return fmt.Errorf("writing attestation: %w", err)
			}

			return nil
		},
	}
	opts.AddFlags(attestCmd)
	parentCmd.AddCommand(attestCmd)
}
