# Copyright 2023 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing
      packages: write # needed for pushing the images to ghcr.io

    env:
      COSIGN_YES: "true"

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true

      - name: Determine Go versions
        id: versions
        uses: carabiner-dev/actions/go/versions@32587e82f960d49b36101e8c45d1956e511965d3 # v1.2.9

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ steps.versions.outputs.GO_MINOR_VERSION_STABLE }}
          check-latest: true
          cache: false

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10

      - name: Set tag output
        id: tag
        run: echo "tag_name=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"

      - name: Set LDFLAGS
        id: ldflags
        run: |
            source ./release/ldflags.sh
            goflags=$(ldflags)
            echo "GO_FLAGS="${goflags}"" >> "$GITHUB_ENV"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LDFLAGS: ${{ env.GO_FLAGS }}

      - name: Generate SBOM
        id: sbom
        uses: carabiner-dev/actions/sbom/source@32587e82f960d49b36101e8c45d1956e511965d3 # v1.2.9
        with:
          codebases: "golang:." # Only generate the SBOM for the main go codebase
          push-to-release: ${{ steps.tag.outputs.tag_name }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Log into ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | ko login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: build images
        run: make build-sign-release-images || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  attestation:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # To generate a token for signing
      contents: write # To push the attestation to the release

    needs:
      - release

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Set tag output
        id: tag
        run: echo "tag_name=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"

      - name: Install tejolote
        uses: kubernetes-sigs/release-actions/setup-tejolote@b5b8280a60e6e20607f77068011269b982c60971 # v0.4.5

      - run: |
          tejolote attest --artifacts github://openvex/vexctl/${{ steps.tag.outputs.tag_name }} github://openvex/vexctl/"${GITHUB_RUN_ID}" --output vexctl.intoto.json --sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          files: vexctl.intoto.json
          tag_name: "${{ steps.tag.outputs.tag_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: openvex/vexctl
